In [27]:
import pandas as pd

EMB_PATH = '/home/maorlov/mbd_paper/data/embeddings/multimodal/gigar3B/layer_36.parquet'
TARGETS_PATH = '/home/maorlov/mbd_paper/data/mbd_targets_balanced.parquet'

In [24]:
df_targets = pd.read_parquet(TARGETS_PATH)

In [25]:
df_targets.head()

,client_id,bcard_target,cred_target,zp_target,acquiring_target,fold
4800167,00467f5c4c824f07255b39a50d79a5c01d416597d20686...,0,0,0,1,2
4801271,029f3754652a163fddf2acf1716dcfbcedae8054e1cd2a...,1,0,0,0,2
4803467,077a5df831737df98a59f569822d1d328043617cf5895d...,1,0,0,0,2
4804631,09bb6fe00e059fe40e5ef4787f794605b7b02c2a6acdd4...,0,0,0,1,2
4805363,0c160d5c8181575715ceabcf038411ef8c419d94d8f75d...,0,0,1,0,2

In [28]:
df_emb = pd.read_parquet(EMB_PATH)

In [ ]:
df_emb.shape

(69474, 3)

In [ ]:
df_emb['client_id'][0]

'0002a012099252d1d5fcbcae6709752441dc24d2cca69483c3d4ad78e13befbe'

In [ ]:
df_emb[df_emb.client_id=="0002a012099252d1d5fcbcae6709752441dc24d2cca69483c3d4ad78e13befbe"]

                                           client_id   embed_0   embed_1
0  0002a012099252d1d5fcbcae6709752441dc24d2cca694...  1.208919 -0.469977

In [ ]:
df_emb.client_id.nunique()

69474

In [ ]:
df_emb.drop_duplicates().shape

(69474, 3)

In [ ]:
df = df_emb.merge(df_targets, on="client_id")

In [ ]:
df.shape

(69474, 8)

In [ ]:
df.head()

,client_id,embed_0,embed_1,bcard_target,cred_target,zp_target,acquiring_target,fold
0,0002a012099252d1d5fcbcae6709752441dc24d2cca694...,1.208919,-0.469977,0,0,0,1,3
1,0003167a31969f58ec49b99b7f84a63aa6646918a12ff1...,1.212777,-0.455241,0,0,0,0,1
2,00033f3bc0c23d130754a282d27ea4519679ad74652562...,1.220997,-0.556603,0,0,0,0,2
3,00034433a7657ae14e1dcb78db08d321d2d05380621f1e...,1.418323,-0.919592,0,0,0,0,2
4,0004b415fa0adf174bf9406df2b01b106fcee7429c2fd4...,1.272974,-0.891726,0,0,0,0,4

In [ ]:
df_emb['client_id'][0]

'00118f6b9666597ae7f4983d1383e91ad4d9899c17ba375543b3b78d47d2ced9_month=12'

In [2]:
import pandas as pd

EMB_PATH = f'../data/embeddings/baselines/'
TARGETS_PATH = '../data/mbd_targets_balanced.parquet'

def format_embedding_data_and_save(emb_name):
    
    df_emb = pd.read_parquet(EMB_PATH + emb_name + '/')

    emb_i = 0

    renamed = dict()
    for i, col in enumerate(df_emb.columns):
        renamed[col] = col
        if col.startswith("emb_"):
            renamed[col]  = f'embed_{emb_i}'
            emb_i += 1

    df_emb.client_id = df_emb.client_id.apply(lambda x: x.split('_')[0])
    df_emb.rename(columns=renamed, inplace=True)
    df_emb.drop(['target_1', 'target_2', 'target_3', 'target_4'], axis=1, inplace=True)

    df_targets = pd.read_parquet(TARGETS_PATH, columns=['client_id'])

    df = df_emb.merge(df_targets, on="client_id")
    df.to_parquet(EMB_PATH + f'/{emb_name}.parquet', index=False)
    print(df.shape)
    
    return df

In [44]:
emb_name = 'lf_trxgeo_tabgpt_lastmonth'

format_embedding_data_and_save(emb_name).head()

(69474, 577)

,client_id,embed_0,embed_1,embed_2,embed_3,embed_4,embed_5,embed_6,embed_7,embed_8,...,embed_566,embed_567,embed_568,embed_569,embed_570,embed_571,embed_572,embed_573,embed_574,embed_575
0,001d594ac99cba858e135502c1981eda0de562c59a4ab4...,2.296472,1.325167,0.037456,1.046072,0.469306,2.205832,-0.701352,1.109294,0.096672,...,0.382956,0.209521,0.229693,0.246261,0.204976,0.289042,0.387542,0.214062,0.263092,0.297806
1,061b16ea6fd1fd23c7044c46ca6b3e08ba62147feff81e...,3.580638,2.593107,1.186304,2.356725,0.660018,0.228893,-0.403089,1.360986,0.930999,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,06fca4b2d4db6cb2db28768a1bd07ce30ad7d495175e94...,0.019033,0.034867,0.401135,-1.570582,1.378739,1.117682,0.694905,1.946263,-0.030254,...,0.315263,0.252661,0.247981,0.224422,0.193164,0.243216,0.193199,0.229384,0.123071,0.313953
3,07709e6798c8482b670f23ee083676eb05f0c4966a9f1d...,1.369702,3.123629,-1.931086,-0.939346,0.719190,2.142745,-0.312887,0.011917,0.374187,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,07947a96530d34b0260635bffd3097c641c87ee4624101...,3.651055,1.650972,0.807916,2.007598,0.364862,0.985129,-0.182922,0.695681,0.228906,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [45]:
emb_name = 'lf_trxgeo_tabbert_lastmonth'

format_embedding_data_and_save(emb_name).head()

(69474, 145)

,client_id,embed_0,embed_1,embed_2,embed_3,embed_4,embed_5,embed_6,embed_7,embed_8,...,embed_134,embed_135,embed_136,embed_137,embed_138,embed_139,embed_140,embed_141,embed_142,embed_143
0,001d594ac99cba858e135502c1981eda0de562c59a4ab4...,-1.198295,-0.086874,-0.763943,0.016850,0.675302,0.004984,0.259461,1.287522,-0.453335,...,-0.442920,0.578043,1.224722,0.538773,0.916366,0.293377,1.271112,-0.555543,-0.302759,-1.020016
1,061b16ea6fd1fd23c7044c46ca6b3e08ba62147feff81e...,-1.564955,0.000260,-0.014943,1.136769,0.375274,0.298813,0.397106,0.303842,-1.798963,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,06fca4b2d4db6cb2db28768a1bd07ce30ad7d495175e94...,-0.012875,-0.472387,0.795837,0.363319,1.285588,-1.084790,0.922346,0.198793,-0.577344,...,0.503475,0.242798,1.315701,0.322484,0.079830,-0.136313,0.883318,-0.435870,0.269679,-1.299427
3,07709e6798c8482b670f23ee083676eb05f0c4966a9f1d...,-0.216894,1.980233,0.022345,-0.015980,-0.002939,-0.483875,-0.959875,1.532088,-0.957604,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,07947a96530d34b0260635bffd3097c641c87ee4624101...,-0.970254,0.321946,-0.405045,0.217681,-0.690489,-0.782805,-0.365331,0.160269,-0.740871,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [48]:
emb_name = 'lf_trxgeo_agg_lastmonth'

format_embedding_data_and_save(emb_name).head()

(69474, 458)

,client_id,embed_0,embed_1,embed_2,embed_3,embed_4,embed_5,embed_6,embed_7,embed_8,...,embed_447,embed_448,embed_449,embed_450,embed_451,embed_452,embed_453,embed_454,embed_455,embed_456
0,001d594ac99cba858e135502c1981eda0de562c59a4ab4...,256.0,1.144419e+07,44703.855469,80005.460938,0.0,84.0,24.0,75.0,4.0,...,0.0,0.0,0.0,0.0,12.0,1.0,256.0,16.0,27.0,18.0
1,061b16ea6fd1fd23c7044c46ca6b3e08ba62147feff81e...,256.0,1.221397e+07,47710.808594,123194.734375,0.0,23.0,0.0,75.0,43.0,...,0.0,0.0,0.0,0.0,7.0,1.0,0.0,0.0,0.0,0.0
2,06fca4b2d4db6cb2db28768a1bd07ce30ad7d495175e94...,2.0,3.901866e+04,19509.330078,21675.031250,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,1.0,130.0,7.0,8.0,9.0
3,07709e6798c8482b670f23ee083676eb05f0c4966a9f1d...,256.0,3.265915e+07,127574.820312,285700.750000,0.0,151.0,86.0,0.0,1.0,...,0.0,0.0,0.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0
4,07947a96530d34b0260635bffd3097c641c87ee4624101...,221.0,1.252102e+07,56656.199219,187889.343750,0.0,40.0,0.0,41.0,3.0,...,0.0,0.0,0.0,0.0,10.0,1.0,0.0,0.0,0.0,0.0

In [49]:
emb_name = 'trx_tabgpt_lastmonth'

format_embedding_data_and_save(emb_name).head()

(69474, 289)

,client_id,embed_0,embed_1,embed_2,embed_3,embed_4,embed_5,embed_6,embed_7,embed_8,...,embed_278,embed_279,embed_280,embed_281,embed_282,embed_283,embed_284,embed_285,embed_286,embed_287
0,001d594ac99cba858e135502c1981eda0de562c59a4ab4...,2.296472,1.325167,0.037456,1.046072,0.469306,2.205832,-0.701352,1.109294,0.096672,...,0.406073,0.500601,0.355711,0.396193,0.375556,0.717510,0.644315,0.553257,0.610398,0.574990
1,061b16ea6fd1fd23c7044c46ca6b3e08ba62147feff81e...,3.580638,2.593107,1.186304,2.356725,0.660018,0.228893,-0.403089,1.360986,0.930999,...,0.339734,0.554927,0.303283,0.442187,0.374390,0.766568,0.610202,0.616211,0.551025,0.529287
2,06fca4b2d4db6cb2db28768a1bd07ce30ad7d495175e94...,0.019033,0.034867,0.401135,-1.570582,1.378739,1.117682,0.694905,1.946263,-0.030254,...,1.487218,1.759263,2.281224,0.986929,0.796298,0.789241,2.119309,1.728596,1.185499,1.705081
3,07709e6798c8482b670f23ee083676eb05f0c4966a9f1d...,1.369702,3.123629,-1.931086,-0.939346,0.719190,2.142745,-0.312887,0.011917,0.374187,...,0.247620,0.296649,0.302915,0.285024,0.259403,0.489909,0.299392,0.366824,0.322383,0.338246
4,07947a96530d34b0260635bffd3097c641c87ee4624101...,3.651055,1.650972,0.807916,2.007598,0.364862,0.985129,-0.182922,0.695681,0.228906,...,0.288475,0.508973,0.290449,0.382847,0.390171,0.688170,0.679082,0.618250,0.610750,0.450815

In [50]:
emb_name = 'trx_tabbert_lastmonth'

format_embedding_data_and_save(emb_name).head()

(69474, 73)

,client_id,embed_0,embed_1,embed_2,embed_3,embed_4,embed_5,embed_6,embed_7,embed_8,...,embed_62,embed_63,embed_64,embed_65,embed_66,embed_67,embed_68,embed_69,embed_70,embed_71
0,001d594ac99cba858e135502c1981eda0de562c59a4ab4...,-1.198295,-0.086874,-0.763943,0.016850,0.675302,0.004984,0.259461,1.287522,-0.453335,...,0.020343,0.325587,-0.049424,-0.001961,1.831066,-0.416313,-0.157750,0.268277,-1.001050,0.873874
1,061b16ea6fd1fd23c7044c46ca6b3e08ba62147feff81e...,-1.564955,0.000260,-0.014943,1.136769,0.375274,0.298813,0.397106,0.303842,-1.798963,...,-0.059568,0.100269,0.014626,0.008240,1.605031,-0.965679,-0.043439,0.704385,-0.690891,1.533392
2,06fca4b2d4db6cb2db28768a1bd07ce30ad7d495175e94...,-0.012875,-0.472387,0.795837,0.363319,1.285588,-1.084790,0.922346,0.198793,-0.577344,...,-0.177069,-0.311854,1.458769,0.078729,0.486839,-0.354631,1.154717,0.345801,-1.000713,1.206203
3,07709e6798c8482b670f23ee083676eb05f0c4966a9f1d...,-0.216894,1.980233,0.022345,-0.015980,-0.002939,-0.483875,-0.959875,1.532088,-0.957604,...,-0.043824,0.115928,0.821112,-0.130298,1.500843,-0.595321,0.215120,0.051836,0.199263,1.624300
4,07947a96530d34b0260635bffd3097c641c87ee4624101...,-0.970254,0.321946,-0.405045,0.217681,-0.690489,-0.782805,-0.365331,0.160269,-0.740871,...,-0.335657,-0.446274,0.102277,-0.122319,1.463452,-1.517490,0.606860,0.810218,-0.812735,1.004310

In [52]:
emb_name = 'trx_agg_lastmonth'

format_embedding_data_and_save(emb_name).head()

(69474, 454)

,client_id,embed_0,embed_1,embed_2,embed_3,embed_4,embed_5,embed_6,embed_7,embed_8,...,embed_443,embed_444,embed_445,embed_446,embed_447,embed_448,embed_449,embed_450,embed_451,embed_452
0,001d594ac99cba858e135502c1981eda0de562c59a4ab4...,256.0,1.144419e+07,44703.855469,80005.460938,0.0,84.0,24.0,75.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,1.0
1,061b16ea6fd1fd23c7044c46ca6b3e08ba62147feff81e...,256.0,1.221397e+07,47710.808594,123194.734375,0.0,23.0,0.0,75.0,43.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,1.0
2,06fca4b2d4db6cb2db28768a1bd07ce30ad7d495175e94...,2.0,3.901866e+04,19509.330078,21675.031250,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
3,07709e6798c8482b670f23ee083676eb05f0c4966a9f1d...,256.0,3.265915e+07,127574.820312,285700.750000,0.0,151.0,86.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0
4,07947a96530d34b0260635bffd3097c641c87ee4624101...,221.0,1.252102e+07,56656.199219,187889.343750,0.0,40.0,0.0,41.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,1.0

In [4]:
emb_name = 'lf_trxgeo_coles_lastmonth'

format_embedding_data_and_save(emb_name).head()

(69474, 513)

,client_id,embed_0,embed_1,embed_2,embed_3,embed_4,embed_5,embed_6,embed_7,embed_8,...,embed_502,embed_503,embed_504,embed_505,embed_506,embed_507,embed_508,embed_509,embed_510,embed_511
0,001d594ac99cba858e135502c1981eda0de562c59a4ab4...,0.043713,0.994445,0.005850,-0.951517,-0.135734,0.219643,0.218723,-0.096065,0.448838,...,-0.138356,0.858756,-0.719390,-0.633159,-0.035703,-0.107879,-0.379315,0.804910,0.123696,0.126205
1,061b16ea6fd1fd23c7044c46ca6b3e08ba62147feff81e...,0.948832,0.998061,0.094398,-0.331879,-0.590662,0.094765,-0.295771,-0.780425,-0.169946,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,06fca4b2d4db6cb2db28768a1bd07ce30ad7d495175e94...,-0.043661,0.722283,-0.101239,-0.540954,-0.123680,0.129089,0.057349,-0.054793,-0.835918,...,-0.118708,0.655710,-0.680139,-0.151572,-0.670734,-0.240890,-0.419028,0.781167,-0.521736,0.204867
3,07709e6798c8482b670f23ee083676eb05f0c4966a9f1d...,0.027630,0.906770,-0.399114,-0.183654,0.061227,0.069242,-0.058849,-0.050796,0.012322,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,07947a96530d34b0260635bffd3097c641c87ee4624101...,0.784880,0.999089,-0.015627,-0.906655,-0.421795,0.081990,-0.473614,-0.658693,0.039836,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [3]:
emb_name = 'trx_coles_lastmonth'

format_embedding_data_and_save(emb_name).head()

(69474, 257)

,client_id,embed_0,embed_1,embed_2,embed_3,embed_4,embed_5,embed_6,embed_7,embed_8,...,embed_246,embed_247,embed_248,embed_249,embed_250,embed_251,embed_252,embed_253,embed_254,embed_255
0,001d594ac99cba858e135502c1981eda0de562c59a4ab4...,0.043713,0.994445,0.005850,-0.951517,-0.135734,0.219643,0.218723,-0.096065,0.448838,...,0.082681,-0.031149,-0.428183,-0.151230,0.995067,0.297059,0.170655,-0.031199,-0.087291,0.066716
1,061b16ea6fd1fd23c7044c46ca6b3e08ba62147feff81e...,0.948832,0.998061,0.094398,-0.331879,-0.590662,0.094765,-0.295771,-0.780425,-0.169946,...,-0.192141,0.006205,0.144469,-0.982645,0.996871,-0.089921,-0.784804,-0.282521,-0.085705,0.134050
2,06fca4b2d4db6cb2db28768a1bd07ce30ad7d495175e94...,-0.043661,0.722283,-0.101239,-0.540954,-0.123680,0.129089,0.057349,-0.054793,-0.835918,...,-0.039698,0.170009,-0.025811,0.143618,0.763928,-0.370425,-0.027312,0.223817,-0.094687,0.017071
3,07709e6798c8482b670f23ee083676eb05f0c4966a9f1d...,0.027630,0.906770,-0.399114,-0.183654,0.061227,0.069242,-0.058849,-0.050796,0.012322,...,0.023112,0.008828,-0.061312,-0.226480,0.935078,0.342598,-0.662755,-0.233266,-0.037437,-0.005306
4,07947a96530d34b0260635bffd3097c641c87ee4624101...,0.784880,0.999089,-0.015627,-0.906655,-0.421795,0.081990,-0.473614,-0.658693,0.039836,...,-0.247380,0.224547,-0.072752,-0.898684,0.996655,-0.085729,0.979442,-0.646209,-0.084583,-0.146894

In [4]:
import pandas as pd

rename_columns = {'target_1': 'bcard_target', 'target_2': 'cred_target', 'target_3': 'zp_target', 'target_4': 'acquiring_target'}

pd.read_parquet('/home/maorlov/mbd_paper/data/embeddings/baselines/last_month/late_fusion/agg/fold=0/test.parquet').rename(columns=rename_columns).head()

,client_id,bcard_target,cred_target,zp_target,acquiring_target,emb_0000,emb_0001,emb_0002,emb_0003,emb_0004,...,emb_0246,emb_0247,emb_0248,emb_0249,emb_0250,emb_0251,emb_0252,emb_0253,emb_0254,emb_0255
0,00579a6cc99b53c0fa79f813ea8cc34f1e6aa09eb37d4f...,0,0,0,0,0.298366,0.535447,-0.083446,-0.573958,-0.265484,...,-0.317231,-0.060374,0.042560,0.413900,0.768588,0.094064,0.055115,0.003802,-0.091018,0.147630
1,012b7244e57fd1ccaad29d4225d2a24ab93ff1572fa302...,0,0,0,0,0.868443,0.769355,0.202038,-0.067177,0.014362,...,0.293143,0.000382,0.057696,0.731915,0.973533,0.072440,-0.926190,-0.022451,-0.225116,0.389506
2,020f1154cab4336a142c3060e48c993a7b495be79780f6...,0,0,0,0,0.191745,0.839612,0.213909,0.226578,-0.077913,...,-0.333231,0.075260,-0.730918,0.247620,0.923234,-0.050767,0.317160,0.045830,0.116133,0.186576
3,021eb7bea95d550d0c4e80d57e35daf995f09382dec3e8...,0,0,0,0,0.766099,0.678563,0.688382,-0.804020,0.048352,...,-0.230825,0.118207,-0.044001,0.037162,0.974247,-0.071939,-0.200537,0.812487,-0.868996,0.022978
4,037c75196fe3c60e4d06f661ef46c222dec74390f22058...,0,0,0,0,-0.176026,0.560471,-0.142692,-0.949513,-0.127475,...,0.118844,0.217185,-0.069214,0.250924,0.757957,-0.177219,0.027620,0.103508,-0.091968,-0.134240

In [4]:
import pandas as pd
pd.read_parquet('/home/maorlov/mbd_paper/data/embeddings/baselines/last_month/late_fusion/agg/fold=0/dataset.parquet').head()

,client_id,embed_0,embed_1,embed_2,embed_3,embed_4,embed_5,embed_6,embed_7,embed_8,...,embed_447,embed_448,embed_449,embed_450,embed_451,embed_452,embed_453,embed_454,embed_455,embed_456
0,00467f5c4c824f07255b39a50d79a5c01d416597d20686...,256.0,2.186067e+07,85393.226562,133408.593750,0.0,151.0,20.0,26.0,0.0,...,0.0,0.0,0.0,0.0,11.0,1.0,256.0,8.0,17.0,24.0
1,029f3754652a163fddf2acf1716dcfbcedae8054e1cd2a...,94.0,6.648647e+06,70730.289062,325701.500000,0.0,13.0,64.0,0.0,15.0,...,0.0,0.0,0.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0
2,077a5df831737df98a59f569822d1d328043617cf5895d...,5.0,2.971483e+05,59429.656250,87196.445312,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0
3,09bb6fe00e059fe40e5ef4787f794605b7b02c2a6acdd4...,256.0,9.963202e+06,38918.757812,62100.367188,0.0,149.0,107.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,1.0,256.0,8.0,10.0,20.0
4,0c160d5c8181575715ceabcf038411ef8c419d94d8f75d...,18.0,1.816573e+06,100920.734375,186609.421875,0.0,15.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,3.0,1.0,256.0,12.0,15.0,12.0